name: Publish Release

on:
  release:
    types: ["published"]

jobs:
  publish:

    env:
      GCLOUD_PROJECT_ID: ${{ vars.GCLOUD_PROJECT_ID }}
      PUBSUB_TOPIC_ID: ${{ vars.PUBSUB_TOPIC_ID }}
      PUBSUB_SUBSCRIPTION_ID: ${{ vars.PUBSUB_SUBSCRIPTION_ID }}
      BEWORKS_GITHUB_TOKEN: ${{ secrets.BEWORKS_GITHUB_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: 'gcp_credentials.json'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up GCP Credentials
      run: echo "${{ secrets.GCP_SA_KEY_BASE_64 }}" | base64 -d > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14.x'

    - name: Configure Git for private repo access
      run: |
        git config --global url."https://x-access-token:${{ env.BEWORKS_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Install dependencies
      run: |
        python -m venv ./.venv
        source ./.venv/bin/activate
        pip install --upgrade pip
        pip install -e .

    - name: Type Checking (MyPy)
      run: |
        source ./.venv/bin/activate
        echo -e '\n\n>>> Starting mypy analysis...\n\n'
        mypy .

    - name: Type Checking (BasedPyright)
      run: |
        source ./.venv/bin/activate
        echo -e '\n\n>>> Starting basedpyright analysis...\n\n'
        basedpyright .

    - name: Unit Tests (pytest)
      run: |
        source ./.venv/bin/activate
        pytest -v --showlocals

    - name: Build
      run: |
        find . -type d -name '*.egg-info' -exec rm -rf -- {} +
        source ./.venv/bin/activate
        python -m build

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*